#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# A wizard reads from the keyboard. Run through a non-interactive front end (Claude Code's
# `!` prefix, a pipe, cron) stdin is not a TTY, every `read` returns empty at once, and the
# wizard races through every stage and exits at the first required value having stored
# nothing — which is what happened on 2026-09-03. Refuse instead, and say where to run it.
if [[ ! -t 0 ]]; then
  printf '\n  This wizard needs an interactive terminal: stdin is not a TTY, so it cannot wait\n'
  printf '  for you or read the token you paste. Run it in your own shell window:\n\n'
  printf '      bash %s\n\n' "$0"
  printf '  (The `!` prefix in Claude Code and pipes both detach the keyboard.)\n\n'
  exit 2
fi

TOTAL_STAGES=5

banner "Provision CORPUS_PIN_TOKEN"

# ── 1. The org policy that silently zeroes everything ─────────────────────
stage "OregonAI — allow fine-grained tokens"
say "A fine-grained PAT scoped to an ORG does nothing unless the org permits"
say "that class of token. This is the first thing to check, because when it is"
say "off the token still issues, still looks valid, and has access to nothing."
open_url "https://github.com/organizations/OregonAI/settings/personal-access-tokens"
step "Under 'Fine-grained personal access tokens', make sure access is ALLOWED."
step "If it offers 'Require administrator approval', either turn it off or be"
step "  ready to approve your own token at the end of stage 2."
pause "Allowed? Press Enter."

# ── 2. Create the token ───────────────────────────────────────────────────
stage "Create the token"
say "Four settings matter. The fourth is the one that is always missed."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: corpus-pin-token"
step "Resource owner: OregonAI  <-- NOT your personal account. This is the"
step "  single commonest mistake; the default is your own user, and a token"
step "  owned by you cannot see org repos however you scope it."
step "Expiration: your call. Fine-grained tokens cap at 1 year — whatever you"
step "  pick, this wizard is committed at scripts/provision-pin-token.sh so"
step "  the re-run is one command rather than an archaeology session."
step "Repository access: 'Only select repositories', then add:"
say  "    executive-regulatory-frameworks   oregon-legislature"
say  "    oregon-budget                     oregon-audits"
say  "    oregon-kpm                        oregon-counties"
say  "    oregon-collective-bargaining      federal-reference"
say  "    corpus-template                   corpus-gateway"
say  "    corpus-chat                       oregon-stories"
note "(the last three are consumer/stories repos — see docs/adr/0002)"
step "Permissions — Repository permissions, set exactly these three:"
say  "    Contents .......... Read and write   (clone, branch, push)"
say  "    Pull requests ..... Read and write   (gh pr create)"
say  "    Workflows ......... Read and write   <-- THE ONE THAT IS MISSED"
warn "Without 'Workflows', the push is REJECTED, not degraded. bump_pins.py"
note "  scans .github/workflows/*.yml (SCAN_GLOBS), so every bump touches a"
note "  workflow file, and GitHub refuses a token that edits one without this."
note "  The error names the file, never the permission — hours, reliably."
say  "Metadata: Read — added automatically, leave it."
step "Generate token, then copy it. It is shown once."
ask_secret PIN_TOKEN "Paste the token (hidden):"
if [[ -z "${PIN_TOKEN:-}" ]]; then
  warn "no token entered — nothing further can be verified or stored."
  exit 1
fi

# ── 3. Verify BEFORE storing ──────────────────────────────────────────────
stage "Verify the token actually works"
say "Storing an unverified credential is how this job came to report success"
say "while doing nothing for three releases (corpus-toolkit#83). Check first."
ok=true
for repo in corpus-template executive-regulatory-frameworks oregon-audits; do
  perms=$(GH_TOKEN="$PIN_TOKEN" gh api "repos/OregonAI/$repo" --jq '.permissions.push' 2>/dev/null || echo "")
  case "$perms" in
    true)  printf '  %s✓%s %s — push: true\n' "$GREEN" "$RESET" "$repo" ;;
    false) printf '  %s✗%s %s — reachable but NO WRITE\n' "$RED" "$RESET" "$repo"; ok=false ;;
    *)     printf '  %s✗%s %s — not reachable with this token\n' "$RED" "$RESET" "$repo"; ok=false ;;
  esac
done
if [[ "$ok" != true ]]; then
  warn "Something is wrong. In order of likelihood:"
  note "  1. Resource owner was your user, not OregonAI (redo stage 2)"
  note "  2. The org requires approval and the token is still pending"
  note "  3. That repo was not in the selected list"
  confirm "Store it anyway?" || exit 1
fi
note "Note: this proves Contents write. It cannot prove the Workflows"
note "permission — only a real push can, which is stage 5."

# ── 4. Store it ───────────────────────────────────────────────────────────
stage "Store as CORPUS_PIN_TOKEN"
say "Set on OregonAI/corpus-toolkit, the repo whose release triggers propagation."
if ! gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null | grep -q "OregonAI/corpus-toolkit"; then
  warn "This is not a corpus-toolkit checkout — 'gh secret set' targets the"
  warn "current repo, so it would land on the wrong one. cd to ~/corpus-toolkit"
  warn "and re-run. Nothing has been stored."
  exit 1
fi
set_secret CORPUS_PIN_TOKEN "$PIN_TOKEN"
note "Deliberately NOT written to .env. Its only destination is a CI secret,"
note "so a copy on disk would be pure added exposure."

# ── 5. Prove the loop ─────────────────────────────────────────────────────
stage "Prove it"
say "A dry run checks out each target repo with the token and stops short of"
say "pushing — so it proves auth and reachability without opening anything."
if confirm "Trigger a dry run against v1.25.0 now?"; then
  gh workflow run propagate-pin.yml -f tag=v1.25.0 -f dry-run=true 2>/dev/null \
    && say "Triggered. Watch: gh run watch \$(gh run list --workflow propagate-pin.yml --limit 1 --json databaseId --jq '.[0].databaseId')" \
    || warn "Could not trigger — run it from the Actions tab instead."
  say ""
  say "What to look for: the 'Check the token' step must NOT print"
  say "  'CORPUS_PIN_TOKEN is not set ... Reporting only.'"
  say "If it still does, the secret did not land."
else
  note "Skipped. Trigger later with:"
  note "  gh workflow run propagate-pin.yml -f tag=v1.25.0 -f dry-run=true"
fi
say ""
warn "The dry run does NOT exercise the push, so it cannot catch a missing"
warn "Workflows permission. The real proof is the first non-dry run — do that"
warn "after the matrix fix for corpus-toolkit#83 lands, so the two dead targets"
warn "are gone and a red leg means something."

finish
