#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# A wizard reads from the keyboard. Run through a non-interactive front end (Claude Code's
# `!` prefix, a pipe, cron) stdin is not a TTY, every `read` returns empty at once, and the
# wizard races through every stage and exits at the first required value having stored
# nothing — which is what happened on 2026-09-03. Refuse instead, and say where to run it.
if [[ ! -t 0 ]]; then
  printf '\n  This wizard needs an interactive terminal: stdin is not a TTY, so it cannot wait\n'
  printf '  for you or read the token you paste. Run it in your own shell window:\n\n'
  printf '      bash %s\n\n' "$0"
  printf '  (The `!` prefix in Claude Code and pipes both detach the keyboard.)\n\n'
  exit 2
fi

TOTAL_STAGES=5

banner "Provision DRIFT_BOT_TOKEN (one org secret, two jobs)"

# ── 1. Why, and the org policy that would silently zero it ────────────────
stage "What this token is for, and the org policy"
say "Two things Actions' built-in token cannot do, both measured on 2026-09-03:"
say "  1. open the monthly drift PR in this org (\"GitHub Actions is not permitted"
say "     to create or approve pull requests\") — and even where that setting is"
say "     on, a PR the built-in token opens runs NO CI, so it can never merge itself;"
say "  2. move the floating 'v1' tag onto a release that changed a reusable"
say "     workflow (\"without 'workflows' permission\")."
say "CORPUS_PIN_TOKEN cannot do the second either: it is scoped to twelve repos and"
say "corpus-toolkit is not one of them. So: ONE new token, ALL repos, three permissions,"
say "stored once at the org. Every corpus already passes 'secrets: inherit'."
say ""
say "First the org policy. A fine-grained PAT owned by OregonAI does nothing unless"
say "the org permits that class of token — it still issues, still looks valid, and"
say "reaches nothing. You did this for CORPUS_PIN_TOKEN; confirm it is still on."
open_url "https://github.com/organizations/OregonAI/settings/personal-access-tokens"
step "Under 'Fine-grained personal access tokens', access must be ALLOWED."
step "If 'Require administrator approval' is on, approve your own token after stage 2."
pause "Allowed? Press Enter."

# ── 2. Create the token ───────────────────────────────────────────────────
stage "Create the token"
say "Five settings. The second and the fourth are the ones that have bitten before."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: drift-bot-token"
step "Resource owner: OregonAI   <-- NOT your personal account. A token owned by"
step "  you cannot see org repos however you scope it."
step "Expiration: your call (fine-grained tokens cap at 1 year). This wizard is"
step "  committed at scripts/provision-drift-bot-token.sh; the re-run is one command."
step "Repository access: ALL REPOSITORIES.   <-- not 'only select'. CORPUS_PIN_TOKEN"
step "  was 'only select' and left corpus-toolkit out, which is why v1.34.1 and"
step "  v1.34.2 were proven by the gate and still could not move 'v1'. 'All' also"
step "  means a corpus added next year is covered without touching the token."
step "Permissions — Repository permissions, exactly these three:"
say  "    Contents .......... Read and write   (clone, branch, push, move a tag)"
say  "    Pull requests ..... Read and write   (gh pr create / merge --auto)"
say  "    Workflows ......... Read and write   (a push or tag touching .github/workflows)"
say  "Metadata: Read — added automatically, leave it. Nothing under Organization"
say  "permissions."
step "Generate token, then copy it. It is shown once."
ask_secret BOT_TOKEN "Paste the token (hidden):"
if [[ -z "${BOT_TOKEN:-}" ]]; then
  warn "no token entered — nothing further can be verified or stored."
  exit 1
fi

# ── 3. Verify BEFORE storing ──────────────────────────────────────────────
stage "Verify the token before it is stored"
say "The one repo CORPUS_PIN_TOKEN could not reach is checked first."
ok=true
for repo in corpus-toolkit executive-regulatory-frameworks oregon-kpm corpus-template oregon-stories; do
  perms=$(GH_TOKEN="$BOT_TOKEN" gh api "repos/OregonAI/$repo" --jq '.permissions.push' 2>/dev/null || echo "")
  case "$perms" in
    true)  printf '  %s✓%s %s — push: true\n' "$GREEN" "$RESET" "$repo" ;;
    false) printf '  %s✗%s %s — reachable but NO WRITE\n' "$RED" "$RESET" "$repo"; ok=false ;;
    *)     printf '  %s✗%s %s — not reachable with this token\n' "$RED" "$RESET" "$repo"; ok=false ;;
  esac
done
n_repos=$(GH_TOKEN="$BOT_TOKEN" gh api 'orgs/OregonAI/repos?per_page=100' --jq 'length' 2>/dev/null || echo 0)
say "  repos visible to the token: $n_repos (the org has 17; 'All repositories' shows them all)"
[[ "$n_repos" -ge 14 ]] || { warn "fewer than the org's public repos are visible — was Repository access 'All'?"; ok=false; }
if [[ "$ok" != true ]]; then
  warn "Something is wrong. In order of likelihood:"
  note "  1. Resource owner was your user, not OregonAI (redo stage 2)"
  note "  2. Repository access was 'Only select repositories'"
  note "  3. The org requires approval and the token is still pending"
  confirm "Store it anyway?" || exit 1
fi
note "This proves Contents write and reach. It cannot prove Pull requests or"
note "Workflows — only stage 5's real run can."

# ── 4. Store it at the ORG ────────────────────────────────────────────────
stage "Store as the org secret DRIFT_BOT_TOKEN"
say "An ORG secret, visible to all repositories — not a repo secret: nine repos"
say "run the drift workflow and corpus-toolkit's gate moves 'v1', and one copy"
say "is one rotation. OregonAI is on the free plan, so an org secret reaches"
say "PUBLIC repos only; that is every repo that needs it (gateway and chat are"
say "private and run no drift)."
stored=false
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if printf '%s' "$BOT_TOKEN" | gh secret set DRIFT_BOT_TOKEN --org OregonAI --visibility all >/dev/null 2>&1; then
    WRITTEN_SECRET+=("DRIFT_BOT_TOKEN (org, all repos)")
    printf '  %s✓ set%s org secret DRIFT_BOT_TOKEN, visibility: all repositories\n' "$GREEN" "$RESET"
    stored=true
  fi
fi
if [[ "$stored" != true ]]; then
  warn "gh could not set the org secret (it needs admin:org scope on your gh login)."
  say  "Do it in the browser instead:"
  open_url "https://github.com/organizations/OregonAI/settings/secrets/actions/new"
  step "Name: DRIFT_BOT_TOKEN · Value: the token · Repository access: All repositories"
  pause "Saved? Press Enter."
  SKIPPED=()  # the human just did it by hand
fi
note "Deliberately NOT written to .env: its only destination is a CI secret."

# ── 5. Prove the loop ─────────────────────────────────────────────────────
stage "Prove it on the smallest corpus"
say "oregon-kpm's scheduled workflow runs drift in ~2 minutes. With the secret in"
say "place the run's last step must OPEN a chore/drift PR authored by the bot,"
say "that PR must show checks running, and it must merge itself once they pass."
say "Before tonight that step warned and left the state stranded on a branch."
if confirm "Dispatch oregon-kpm's scheduled workflow now?"; then
  gh workflow run scheduled.yml -R OregonAI/oregon-kpm 2>/dev/null \
    && say "Dispatched. Watch:  gh run watch \$(gh run list -R OregonAI/oregon-kpm --workflow scheduled.yml --limit 1 --json databaseId --jq '.[0].databaseId') -R OregonAI/oregon-kpm" \
    || warn "Could not dispatch — run it from the Actions tab of oregon-kpm."
  say ""
  say "Then:  gh pr list -R OregonAI/oregon-kpm --head chore/drift"
  say "  - a PR exists ............... the token can open PRs"
  say "  - its checks run ............ the PR was not opened by the built-in token"
  say "  - it merges on green ........ auto-merge works; the loop is closed"
  say "If the step is red and names DRIFT_BOT_TOKEN, the secret did not reach the"
  say "workflow: check the org secret's repository access is 'All repositories'."
else
  note "Skipped. Dispatch later with:  gh workflow run scheduled.yml -R OregonAI/oregon-kpm"
fi
say ""
note "Second proof, at the next toolkit release: the gate's advance-major-tag job"
note "moves 'v1' without a hand. Tonight's v1.34.2 needed one."

finish
